# Generated by Django 5.2.2 on 2025-06-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('evaluation_name', models.CharField(max_length=255)),
                ('evaluation_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
